title: Hailong Li's Homepage
page-top-title: Hailong Li
top-section-bg-text: Computer Science
home-subtitle: Hailong Li&ensp;|&ensp;李海龙
copyright-text: '&copy; Hailong Li 2023-2024. All Rights Reserved.'
